[theme]
theme = "native"

[icons]
icons = "awesome6"

[[block]]
block = "focused_window"
[block.format]
full = " $title.str(max_w:25) |"
short = " $title.str(max_w:15) |"

[[block]]
block = "memory"
format = " $icon $mem_used.eng(w:3,u:B,p:M) "

[[block]]
block = "net"
format = " $icon { $signal_strength $ssid| wired} "

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
full_format = " $icon  charged "
format = " $icon  $percentage "
if_command = "test -e /sys/class/power_supply/BAT0"

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%a %h %d %r') "
