# fonts
font-main: &font-main JetBrainsMono Nerd Font:pixelsize=14
icon: &icon Font Awesome 6 Free:pixelsize=13:style=Solid

# colors
fg: &fg e8e4d9ff
bg: &bg 171717ff
grey: &grey 636363ff
red: &red ba423fff

# main bar config
bar:
  height: 20
  location: top
  monitor: '*'
  font: *font-main
  foreground: *fg
  background: *bg
  spacing: 10
  margin: 10
  left-margin: 0

  left:
    - river:
        content:
          map:
            tag: id
            values:
              32: {empty: {}}
            default:
              map:
                tag: occupied
                values:
                  true:
                    map:
                      on-click: sh -c 'riverctl set-focused-tags $((1 << ({id} - 1)))'
                      tag: state
                      values:
                        focused: &focused { string: &river_tag {text: ' {id} '}}
                        urgent: { string: { <<: *river_tag, foreground: *red }}
                        invisible: &invisible { string: { <<: *river_tag, foreground: *grey }}
                        unfocused: *invisible
                  false:
                    map:
                      tag: focused
                      values:
                        true: *focused
                        false: { empty: {} }
  center:
    - river:
        title: { string: {text: '{title}', max: 80} }
        content: { empty: {} }
  right:
    - script:
        path: /home/skovati/.local/bin/ymem
        args: []
        content:
          - string: { text: " ", font: *icon }
          - string: { text: "{mem}mb" }
    - script:
        path: /home/skovati/.local/bin/yvol
        args: []
        content:
          map:
            tag: vol
            default:
              - string: { text: " ", font: *icon }
              - string: { text: "{vol}" }
            values:
              0%:
              - string: { text: " ", font: *icon }
              - string: { text: "{vol}" }
    - network:
        name: wlp3s0
        poll-interval: 10
        content:
          map:
            tag: state
            default: &up
             - string: { text: ' ', font: *icon }
             - string: { text: "{signal}dB" }
            values:
              down: &down
               - string: { text: ' ', font: *icon }
               - string: { text: 'no signal'}
              up:
                map:
                  default: *up
                  tag: ipv4
                  values: # if we don't have an ip, treat as down
                    "": *down
    - battery:
        name: BAT0
        poll-interval: 30
        content:
          list:
            spacing: 4
            items:
              - map:
                  tag: state
                  values:
                    discharging:
                      ramp:
                        tag: capacity
                        items:
                          - string: {text: ' ', font: *icon}
                          - string: {text: ' ', font: *icon}
                          - string: {text: ' ', font: *icon}
                          - string: {text: ' ', font: *icon}
                          - string: {text: ' ', font: *icon}
                    charging:
                      string: &charging {text: ' ', font: *icon}
                    full:
                      string: {<<: *charging}
              - string: {text: '{capacity}%'}
    - clock:
        time-format: '%r'
        date-format: '%a %h %d'
        content:
          list:
            spacing: 3
            items:
            - string: {text: " " }
            - string:
                text: '{date}'
                on-click: riverctl spawn 'alacritty -e "cal -3"'
            - string: {text: '-'}
            - string: {text: '{time}'}
