theme = "native"
icons = "awesome6"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "music"
player = "spotify"
marquee_interval = 0
format = " {combo}"
hide_when_empty = true

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}"

[[block]]
block = "net"
device = "wlp3s0"
format = " {ssid} {signal_strength}"
interval = 5

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
full_format = " charged"
format = " {percentage} {time} {power}"
if_command = "test -e /sys/class/power_supply/BAT0"

[[block]]
block = "time"
interval = 1
format = "%a %h %d %r"
